services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "5173:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0

volumes:
  node_modules: