version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "5173:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev